# Generated by Django 5.1.3 on 2024-11-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock_manager', '0002_alter_customer_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
