# Generated by Django 5.1.3 on 2024-11-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock_manager', '0002_categories_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
