# Generated by Django 5.1.3 on 2024-11-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock_manager', '0003_remove_product_category_delete_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_per_package',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='0x0', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default='0', max_length=10),
        ),
    ]
