# Generated by Django 5.1.3 on 2024-11-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock_manager', '0004_product_quantity_per_package_product_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unity_type',
        ),
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('g', 'Gramas'), ('kg', 'Quilos'), ('un', 'Unidades'), ('m', 'Metros'), ('cm', 'Centímetros')], default='un', max_length=50, verbose_name='Unit Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default='0'),
        ),
    ]
