# Generated by Django 5.1.3 on 2024-11-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock_manager', '0006_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
