# Generated by Django 5.1.3 on 2024-12-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock_manager', '0007_purchase_observations_sale_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='nfe',
            field=models.CharField(default='', max_length=255),
        ),
    ]
