# Generated by Django 5.1.3 on 2024-12-03 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock_manager', '0008_sale_nfe'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('AV', 'À Vista'), ('CR', 'Crédito'), ('BO', 'Boleto')], default='AV', max_length=2),
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='app_stock_manager.sale')),
            ],
        ),
    ]
