# Generated by Django 5.1.3 on 2024-12-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock_manager', '0009_sale_payment_type_boleto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleto',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='boleto',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='boleto',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago')], default='Pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='boleto',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
