# Generated by Django 5.1.5 on 2025-02-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock_manager', '0010_remove_boleto_amount_remove_boleto_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='max_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='min_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
