# Generated by Django 5.1.5 on 2025-02-13 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock_manager', '0012_purchase_supplier_name_sale_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseproduct',
            name='product_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='product_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_products', to='app_stock_manager.product'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_products', to='app_stock_manager.product'),
        ),
    ]
