# Generated by Django 5.1.6 on 2025-02-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock_manager', '0013_purchaseproduct_product_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_quote',
            field=models.BooleanField(default=True),
        ),
    ]
