# Generated by Django 5.1.5 on 2025-05-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock_manager', '0014_sale_is_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('AV', 'À Vista'), ('PX', 'PIX'), ('DB', 'Debito'), ('CR', 'Crédito'), ('BO', 'Boleto')], default='AV', max_length=2),
        ),
    ]
