# Generated by Django 5.1.5 on 2025-05-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock_manager', '0015_alter_sale_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='credit_installments',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
