# Generated by Django 5.2.1 on 2025-06-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock_manager', '0017_manufacturer_alter_product_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
